name = "StatGeochem"
uuid = "df4de05a-b714-11e8-3c2a-c30fb13e804c"
authors = ["C. Brenhin Keller <cbkeller@dartmouth.edu>"]
version = "0.9.5"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
Perple_X_jll = "9c18f8f7-1c8d-5a34-9fc2-3ecefed5c104"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatGeochemBase = "61e559cd-58b4-4257-8528-26bb26ff2b9a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
StatGeochemPlotsExt = "Plots"

[compat]
Colors = "0.10 - 0.13"
DelimitedFiles = "1"
Distributions = "0.25"
Downloads = "1"
FileIO = "1"
HDF5 = "0.13 - 0.17"
ImageIO = "0.1 - 0.6"
LazyArtifacts = "1"
LogExpFunctions = "0.3"
LoopVectorization = "0.12.113"
NaNStatistics = "0.6.3"
Perple_X_jll = "=7.1.9"
Plots = "1"
Polyester = "0.6.1, 0.7"
ProgressMeter = "1"
Reexport = "0.2, 1.0"
StatGeochemBase = "0.6.18"
Statistics = "1"
StructArrays = "0.7"
julia = "1.9"
