name = "StatGeochem"
uuid = "df4de05a-b714-11e8-3c2a-c30fb13e804c"
authors = ["C. Brenhin Keller <cbkeller@berkeley.edu>"]
version = "0.3.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatGeochemBase = "61e559cd-58b4-4257-8528-26bb26ff2b9a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Colors = "0.10 - 0.12"
FileIO = "1"
GR = "0.42 - 0.63"
HDF5 = "0.13 - 0.15"
ImageIO = "0.1 - 0.5"
LoopVectorization = "0.2 - 0.12"
NaNStatistics = "0.6.2"
Plots = "1"
ProgressMeter = "1"
Reexport = "0.2, 1.0"
SpecialFunctions = "0.5 - 0.10, 1, 2"
StatGeochemBase = "0.2, 0.3"
StatsBase = "0.20 - 0.33"
julia = "1"
